version: "3.8"

services:
  teleapp:
    container_name: teleapp
    image: lcwlouis/teleapp:latest
    networks:
      - teleapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db_data:/app/db_data

networks:
  teleapp:
    driver: bridge