services:
  telegpt:
    container_name: telegpt
    image: lcwlouis/telegpt:latest
    restart: always
    networks:
      - telegpt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - telegpt:/app/data

networks:
  telegpt:
    driver: bridge

volumes:
  telegpt: